export const GET_MARKETS = 'GET_MARKETS';
export const GET_MARKET = 'GET_MARKET';
export const SEARCH_MARKETS = 'SEARCH_MARKETS';
export const FILTER_MARKETS = 'FILTER_MARKETS';
export const CLEAR_MARKETS = 'CLEAR_MARKETS';
export const SET_LOADING = 'SET_LOADING';
export const MARKETS_ERROR = 'MARKETS_ERROR';
